### ISSUE TITLE
Il faut dire clairement en 00 et 01 qu'on parle de la reproductibilité des calculs

### ISSUE THREAD

**Issue by khinsen** [rr-france/bookrr#28]
L'introduction à ce livre répète une erreur fréquente : elle suppose que "reproductibilité" veut dire "reproductibilité computationnelle" pour tout le monde. Et pourtant il y a une brève référence à la "crise de la reproductibilité" qui est due à plusieurs facteurs, dont la reproductibilité expérimentale et la reproductibilité statistique.

Proposition :
  1. Caser le mot "computationnel" (où "calcul") quelque part dans la préambule.
  2. Commencer le chapitre 1 par le context générale de la reproductibilité (dans toutes ses formes)
  3. Dire clairement dans 1.2 que ce livre traite uniquement des aspects informatiques.

**Comment by borishejblum** [comment]
Bonjour Konrad,

Merci de votre intérêt pour ce livre, et pour vos propositions. Je précise tout d'abord que, même si le _booksprint_ est lui terminé, notre travail d'édition et de relecture de l'ouvrage n'est pas encore tout à fait finalisé (il le sera d'ici fin mai).

Concernant votre remarque et vos propositions, vous avez tout à fait raison : nous avons délimité la portée du sujet traité dans cette première édition en nous concentrant sur les outils de la recherche reproductible — et non sur la reproductibilité scientifique dans son ensemble. En revanche, ces outils ne sont pas uniquement computationnels (incluant par exemple le cahier de laboratoire) — même s'ils prennent souvent une forme informatique — et nous avons essayé de nous adresser à tous les chercheurs (pas uniquement à ceux faisant du "calcul").

Ce choix éditorial excluant une partie de la question de la reproductibilité de la science est explicité dans le dernier paragraphe du chapitre 1 "État des lieux" (dans le paragraphe intitulé "La minute théologie négative : ce que vous ne trouverez pas dans cet ouvrage"). Néanmoins, il est important que ce choix limitatif apparaisse clairement au lecteur, et votre lecture laisse à penser que ce n'est peut-être pas le cas en l'état actuel. Je vous propose donc de revisiter cette discussion dès que notre travail d'édition et de relecture sera finalisé pour s'assurer que cette délimitation du sujet traité soit effectivement bien claire dès le début du livre.

Enfin, le sujet plus large de la reproductibilité de la science, au delà des outils de la recherche reproductible, pourra potentiellement être traité lors d'éditions futures et augmentées de l'ouvrage.

Boris

**Comment by khinsen** [comment]
Bonjour Boris,

Je suis bien d'accord que l'usage de l'informatique dépasse le calcul dans le sens strict; j'ai commencé à utiliser le terme "recherche assisté par ordinateur" pour cette raison mais pour l'instant je suis le seul à le faire (à ma connaissance).

Concernant le chapitre 1, voici le souci que je vois avec la version actuelle. Il y a aujourd'hui beaucoup de confusion autour des aspects différents de la reproductibilité, même parmi les gens qui s'y intéressent depuis un petit moment. Pour moi le rôle principal d'un chapitre introductoire est de reduire autant que possible cette confusion: bien définir les thèmes qui seront abordés et les termes qui seront utilisés dans le livre, mais aussi les sujets exclus et les termes utilisés par d'autres auteurs et/ou dans d'autres domaines (expériences, ...).

En lisant le texte actuel avec les yeux d'un néophyte, je rencontre d'abord la "crise de la reproductibilité" avec les études cliniques citées comme exemple. C'est donc l'aspect statistique de la reproductibilité. Par la suite, j'apprends que le terme "reproductibilité" est utilisé dans beaucoup de sens, mais que le terme "recherche reproductible" désigne uniquement l'amélioration des pratiques informatiques, même s'il y a "des nombreuses définitions" (à ma connaissance il n'y en a que deux pour l'aspect informatique). Encore une section plus loin, c'est tout le débat sur la reproductibilité qui est décrit comme tournant autour des aspects informatiques - ce qui n'est pas vrai non plus. Par la suite, la question "Suis-je vraiment sûr de mon analyse statistique ?" est présentée comme un sujet clé de la reproductibilité - mais en réalité, elle fait beaucoup plus référence à l'absence d'erreurs, que la reproductibilité ne garantit pas, comme c'est bien dit quelques phrases plus tard.

Pour moi tout contribue plutôt au maintien de la confusion, ce que je trouve bien dommage.

Konrad.

**Comment by rougier** [comment]
Merci pour la relecture Konrad. On a encore du boulot sur cette introduction qu'on a visiblement pas assez relue (les limites du booksprint). On voulait évoquer la notion de reproductibilité sans pour autant  définir le terme sachant que les pratiques différent selon les domaines scientifiques et nous comptions sur  le fait que les personnes peuvent avoir une intuition raisonnable de ce que cela signifie dans leur propre domaine. Dans le même temps, on souhaitait expliquer avant tout qu'il est possible de mettre en place les pratiques de la recherche reproductible et qu'elles ne ramènent pas toutes à l'informatique et au calcul. Mais je m'aperçois qu'on a un paragraphe avec une définition :(

Sur le premier exemple des études pré-cliniques, je ne comprends ta remarque sur l'aspect statistique. Les causes de non-reproductibilité peuvent être nombreuses, comme par un exemple un mauvais protocole de collecte,  un biais de sélection, etc. Ou bien tu expliques que c'est nous qui faisons ce raccourci ?

**Comment by khinsen** [comment]
Laisser la définition floue, ça me va aussi - mais là encore, il vaut mieux le dire clairement (genre: "il y a beaucoup de définitions parfois contradictoires en cours, notre but dans ce chapitre n'est pas de participer à ce jeux mais plutôt de parler des enjeux pour la science de la problématique dans son ensemble, avant de passer aux questions pragmatiques.") 

Quant aux études pré-cliniques, je me souviens d'une présentation par un médecin qui disait que les aspects statistiques (p-hacking etc.) étaient le souci principal dans ce domaine. Pas de référence, désolé. Il y a forcement d'autres aspects qui interviennent, comme toujours.

**Comment by alegrand** [comment]
Salut,

  j'ai refait une passe en essayant de prendre les retours de Konrad en compte afin de clarifier les choses. Il me semble que les ambiguités sont maintenant levées. On précise maintenant clairement que:
- La crise de reproductibilité peut avoir des "causes structurelles qui soumettent les chercheurs à une pression accrue et qui peuvent conduire à des conduites déviantes sur le plan déontologique mais selon nous la majorité des chercheurs est en général de bonne foi et les causes les plus répandues et les plus insidieuses sont souvent d’ordre méthodologique et technique" et ce juste avant d'enchainer sur le numérique.
- Il y a plusieurs définitions (on en donne clairement deux), qu'on ne cherche pas à prendre position mais àdonner une acceptation large, comme Konrad le suggérait. 
- "Ces solutions ne sont pas uniquement computationnelles — même si elles prennent souvent une forme informatique — et s’adresse à tous les chercheurs (pas uniquement à ceux faisant du “calcul”) et dans la foulée, on précise que les questions de p-hacking, harking, etc. sont hors 

Par contre, sur le fait que les problèmes des études pré-cliniques seraient plus liés aux aspects statistiques qu'à, par exemple, de mauvais protocoles expérimentaux, c'est possible et j'ai entendu des choses allant dans le même sens mais ça n'a rien d'évident. Nous ne prendrons donc pas position. Nous précisons que ces aspects (essentiels) sont hors périmètre mais que nous les traiterons peut-être dans une prochaine édition.

Pour moi, c'est bon. Je suggère que les autres fassent comme moi: impriment le préembule et le chapitre 1 pour le relire tranquilement, voir s'il y a quoi que ce soit qui les choque, et valider (ou pas) mes propositions de modifications. Je vais voir si je peux faire un latex-diff et vous l'envoyer pour que vous les modifications soient plus claires.

**Comment by sabrinagranger** [comment]
qqs citations clés en main et refs complémentaires pour une modeste contribution aux échanges, vous ferez le tri 

**sur l'absence de consensus terminologique**

en plus de la ref de Barba sur la terminologie, il y a aussi Goodman, Steven N., Daniele Fanelli, and John P. A. Ioannidis. ‘What Does Research Reproducibility Mean?’ Science Translational Medicine 8, no. 341 (1 June 2016): 341ps12-341ps12. https://doi.org/10.1126/scitranslmed.aaf5027.
Stark, Philip B. ‘Before Reproducibility Must Come Preproducibility’. News. Nature, 24 May 2018. https://doi.org/10.1038/d41586-018-05256-0. "Contradictory meanings accross disciplines are deeply entrenched"

« Indeed, the very notion of “reproducible research” can be confusing, because its meaning and implications depend on what aspect of research is being examined: the reproducibility of research methods can in principle be expected to be 100%; but the reproducibility of results and inferences is likely to be lower and to vary across subfields and methodologies, for reasons that have nothing to do with questionable research and publication practices »  in 
Fanelli, Daniele. ‘Is Science Really Facing a Reproducibility Crisis, and Do We Need It To?’ Proceedings of the National Academy of Sciences 115, no. 11 (13 March 2018): 2628–31. https://doi.org/10.1073/pnas.1708272114.


 **sur les causes structurelles** 
« Bad methodology, inadequate constraints on researchers, and a professionnal scientific culture that creates incentives to produce new results – innovative results, trailblazing  results, exciting results – have combined to create the reproducibility crisis. » in
Randall, David, and Christopher Welser. The Irreproducibility Crisis of Modern Science. Causes, Consequences, and the Road to Reform. New York: National Association of Scholars, 2018. https://www.nas.org/images/documents/NAS_irreproducibilityReport.pdf.

« The essence of science is doubt. […] Yet there is a paradox in the scientific status quo ; researchers are incentivized, even encouraged, to deemphasize doubt and uncertainty. »  in 
Frankenhuis, Willem, and Daniel Nettle. ‘Open Science Is Liberating and Can Foster Creativity’. Open Science Framework, 18 February 2018. https://doi.org/10.17605/OSF.IO/EDHYM.

**sur l'inadéquation entre les besoins et les cadres éditoriaux (malgré les politiques de mise à disposition des données)**
« Two decades of dizzying technological change have passed. But research publishing seems stuck with those that were employed when it first went online. The majority of content is authored as MS Office documents and submitted and reviewed via dated enterprise software systems which even the largest and best-resourced publishers have struggled to update. A micro-industry of typesetting vendors bash the material into XML files based on complex proprietary DTDs. Distribution platforms spend small fortunes wrestling this into serviceable HTML, while many readers still regard the venerable PDF file format as a gold standard of permanence and portability. […] No MS Word, no typesetters, no complex proprietary formats or display platforms. Systems for submission and review would look a lot like GitHub. Online publication as HTML, ePUB or PDF would happen at the robotic push of a button. Post-publication review or discussion or correction would come free out of the box.»  in
Cornelius, Stephen. ‘Scholarly Publishing Is Stuck in 1999’. Stephen Cornelius (blog), 15 April 2018. https://medium.com/@stphencornelius/scholarly-publishing-is-stuck-in-1999-507ab9bb06f5.

« Second, among the policies that do exist, guidelines vary and are relatively ambiguous. Overall, the biomedical literature is lacking policies that would ensure that underlying data is maximally available and reusable. »  in 
Vasilevsky, Nicole A., Jessica Minnier, Melissa A. Haendel, and Robin E. Champieux. ‘Reproducible and Reusable Research: Are Journal Data Sharing Policies Meeting the Mark?’ PeerJ 5 (25 April 2017): e3208. https://doi.org/10.7717/peerj.3208.

**sur la notion de crise de la reproductibilité**
"I argue that this crisis narrative is at least partially misguided. Recent evidence from metaresearch studies suggests that issues with research integrity and reproducibility, while certainly important phenomena that need to be addressed, are: (i) not distorting the majority of the literature, in science as a whole as well as within any given discipline; (ii) heterogeneously distributed across subfields in any given area, which suggests that generalizations are unjustified; and (iii) not growing, as the crisis narrative would presuppose. Alternative narratives, therefore, might represent a better fit for empirical data as well as for the reproducibility agenda. » in
Fanelli, Daniele. ‘Is Science Really Facing a Reproducibility Crisis, and Do We Need It To?’ Proceedings of the National Academy of Sciences 115, no. 11 (13 March 2018): 2628–31. https://doi.org/10.1073/pnas.1708272114.

voir aussi
« Funding agencies and journals, professional societies and even mass media are paying attention, often focusing on the so-called “crisis” of reproducibility. »  in
Barba, Lorena A. ‘Terminologies for Reproducible Research’. ArXiv:1802.03311 [Cs], 9 February 2018. http://arxiv.org/abs/1802.03311.

**sur les impacts du numérique sur l'ensemble des disciplines et son rôle dans la question de la reproductibilité**
« A general increase in the complexity and scale of experiments and related statistical analyses of results, with increasing specialization and division of labor resulting in lack of clarity around who is actually responsible for quality checks (Leonelli 2017a) » in
Leonelli, Sabina. ‘Re-Thinking Reproducibility as a Criterion for Research Quality’. History of Economic Thought and Methodology, January 2018, 19.

« Since digital computers are exact machines, practitioners apparently assumed that results obtained by computer could be trusted, provided that the principal algorithms and methods employed were suitable to the problem at hand. Little attention was paid to the correctness of implementation, potential for error, or variation introduced by system soft- and hardware, and to how difficult it could be to actually reconstruct after some years—or even weeks—how precisely one had performed a computational experiment. »  in
Plesser, Hans E. ‘Reproducibility vs. Replicability: A Brief History of a Confused Terminology’. Frontiers in Neuroinformatics 11 (2018). https://doi.org/10.3389/fninf.2017.00076.
« However, sudden reliance on computation has created an 'informatics crisis' for life science researchers: computational resources can be difficult to use, and ensuring that computational experiments are communicated well and hence reproducible is challenging » in
Goecks, Jeremy, Anton Nekrutenko, James Taylor, and The Galaxy Team. ‘Galaxy: A Comprehensive Approach for Supporting Accessible, Reproducible, and Transparent Computational Research in the Life Sciences’. Genome Biology 11, no. 8 (2010): R86. https://doi.org/10.1186/gb-2010-11-8-r86.

**Comment by khinsen** [comment]
Salut Arnaud,

j'ai regardé ta révision (branche `intro_rework`), qui est en effet nettement plus claire que la version d'origine.

Et je propose de faire un volume 2 avec rien que les références trouvées par Sabrina, qui sont une mine d'or pour tout auteur dans ce domaine ! Ça ne s'adresse pas au même public, bien sûr, mais ce serait dommage de ne pas mettre en valeur cette belle collection.

**Comment by alegrand** [comment]
Merge effectué. Merci à Konrad pour ce retour et à Sabrina pour sa biblio toujours aussi impressionnante. :)
